# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
    - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
fos_ck_editor:
    configs:
        my_config_1:
            toolbar: "my_config"
            language : fr
            uiColor: "#772953"
    toolbars:
        configs:
            my_config: [ "@document", "-", "@full.paragraph", "-", "@full.styles" ]
        items:
            document: [ "Bold", "-", "Italic", "-", "Strike", "-", "RemoveFormat", "-", "full.paragraph", "-", "Link", "-", "Unlink", "-", "Image" ]
