vich_uploader:
    db_driver: orm

    mappings:
        performer_avatar:
            uri_prefix: /uploads/performer/avatar
            upload_destination: '%kernel.project_dir%/public/uploads/performer/avatar'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
