vich_uploader:
    db_driver: orm

    mappings:
        performer_avatar:
            uri_prefix: /uploads/performer/avatar
            upload_destination: '%kernel.project_dir%/public/uploads/performer/avatar'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        about_background:
            uri_prefix: /uploads/about/background
            upload_destination: '%kernel.project_dir%/public/uploads/about/background'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
